In [2]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.zeros(0)

array([], dtype=float64)

In [7]:
np.full(3, 67)

array([67, 67, 67])

In [9]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
a[2]

np.int64(3)

In [11]:
a[2] = 55
a

array([ 1,  2, 55])

In [12]:
a[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [13]:
a[5] = 24

IndexError: index 5 is out of bounds for axis 0 with size 3

In [14]:
np.arange(4,3)

array([], dtype=int64)

In [15]:
np.arange(4,4)

array([], dtype=int64)

In [16]:
np.arange(4,22)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21])

In [17]:
np.arange(4,22,3)

array([ 4,  7, 10, 13, 16, 19])

In [20]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [22]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
a = np.array([[1,2],[3,4],[2,2]])
a

array([[1, 2],
       [3, 4],
       [2, 2]])

In [28]:
a[2] = np.zeros(2)
a

array([[1, 2],
       [3, 4],
       [0, 0]])

In [31]:
a[1:,0] = 8
a

array([[1, 8],
       [8, 8],
       [8, 8]])

In [32]:
np.random.rand(5,2)

array([[0.24982416, 0.64596942],
       [0.92068325, 0.18596977],
       [0.55655202, 0.209789  ],
       [0.3034192 , 0.71415379],
       [0.68197153, 0.41341573]])

In [33]:
np.random.seed(2)
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [35]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [36]:
np.random.seed(2)
np.random.randint(low=-3, high=22, size=(6,4))

array([[ 5, 12, 10,  5],
       [19,  8, 15,  8],
       [ 5,  4, -1, 14],
       [ 8, 18, 12, 17],
       [17,  2,  4,  0],
       [ 3,  1,  7,  8]])

In [52]:
a = np.arange(2,7)
a

array([2, 3, 4, 5, 6])

In [53]:
b = np.random.randint(0,4,5)
b

array([1, 3, 2, 0, 0])

In [54]:
a > b

array([ True, False,  True,  True,  True])

In [55]:
a[a>b]

array([2, 4, 5, 6])

In [3]:
vec = np.arange(5,13,2)
vec

array([ 5,  7,  9, 11])

In [9]:
mat = np.arange(6).reshape(3,2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
np.concatenate([vec, vec])

array([ 5,  7,  9, 11,  5,  7,  9, 11])

In [6]:
np.hstack([vec,vec])

array([ 5,  7,  9, 11,  5,  7,  9, 11])

In [28]:
mat1 = np.arange(6).reshape(3,2)
mat2 = np.arange(12,36,2).reshape(2,6)
print(mat1)
print(mat2)

[[0 1]
 [2 3]
 [4 5]]
[[12 14 16 18 20 22]
 [24 26 28 30 32 34]]


In [50]:
mat3 = np.random.randint(1,100,(6,5))
mat3

array([[92,  2, 74, 25, 56],
       [87, 16, 36, 41, 40],
       [67, 26, 49, 87, 25],
       [21, 19,  7, 16, 84],
       [35, 74, 45, 98, 57],
       [56, 74, 27, 88, 90]])

In [52]:
mat3[:2]%2==0

array([[ True,  True,  True, False,  True],
       [False,  True,  True, False,  True]])

In [58]:
mat3[mat3[:,:]%2==0].reshape(2,8)

array([[92,  2, 74, 56, 16, 36, 40, 26],
       [16, 84, 74, 98, 56, 74, 88, 90]])

In [65]:
u = np.random.randint(1,10,4)
v = np.random.randint(1,10,4)
X = np.random.randint(-1,4,(4,2))
print("u: ",u)
print("v: ",v)
print("X: \n",X)

u:  [3 8 2 5]
v:  [7 1 5 5]
X: 
 [[ 2  3]
 [ 2  2]
 [-1  0]
 [-1 -1]]


In [60]:
u.dot(v)

np.int64(40)

In [66]:
X.T.dot(u)

array([15, 20])